---
title: "Étude de cas"
output: html_document
---

#Situation départ
cie de transport de colis aérien canadien

#Question 1
Librairy
Extraire les données directement du site
Travail sur les données
visualisation du data
     Faire une carte
          afficher toutes les aéroports
          le flow de trajet en provenance et en arrivé en diagramme à bande et en carte



#Question 2
a)
Les fonctions offre un frame avec les paramètres obligatoires
Fonction calcul de distance 
Sous fonction des times zones
Fonction calcul de temps avec fuseau horaire (vitesse 500 km)
     Time computer (upper floor) + time zone  et date constante
     
Fonction de coûts (prix d'envoie pour un client) {départ, arriver, ...}
     calcul du cost en fonction du poids (avec une loi - poisson/gamma paramétrique), distance et fréquence des vols de l'aéroports et arriver (fonction de survie appliquer sur le prix (fréquence) avec CDF)
     Frais fixe (administration et infrastructure) - constante canadien
     Marge de profit en paramètre (paramètre par défaut) - % constant
     Rabais applicable - % avec valeur de défaut
     Taxes série de case ou if avec Internet
     = prix du transport pour le client
     * vérification des paramètres avec message d'erreur (print)
          Prix pas négatif
          Distance minimale - constante 

b)
Le departement de marketing de Montréal ait de la facilité d'estimer les coûts en fonction du poids et de la distance. Toronto, Calgary et Vancouver (plusieurs graphiques dans même fenêtre)

plot - Repartition de la fonction de coûts (poids varie, le reste non)
plot - Repartition de la fonction de coûts (distance varie, le reste non)



#Question 3 simulation : Prédiction sur les profits annuels
a)
Pour nous: Poids distance compétiteur
Data Excel
Poids aléatoire log normal asymétrique vers la gauche
distance aléatoire lognormal 
génère un data 
Ajustement data:
     on applique un fonction de coûts linéaire (vrai prix)
     Rajoute du bruit (fausser le prix) dans les petits colis et dans les distances moyennes
          En fonction du kappa ->impact du bruit 

lm avec les datas fournis en deux dimensions (coûts et distance)

b)De montréal
On utilise optim pour refiter à partir du data la loi de distribution - Normale, gamma, Lognormal, weibull

Avec la loi de distribution trouver avec optim, on fait de la simulation
     la distribution des clients suit une poisson de paramètre lambda mensuel = variable (rpoisson) (constante)
     
     Distribution trouvée -> simulation annuelle des poids par clients
     simulation des arriver -> 1/417 runif

     
Chaque client prends la cie la moins cher
sur le data on applique notre fonction de coûts et celle du compétiteur on calcul les deux prix.
qui est les moins cher entre les deux (0 et 1)


Calcul les revenus/part de marché des deux compagnies
plot et curve


Supplémentaire:
Travail sur les graphiques
